# 服务端口
server:
  port: 8081


# 数据库配置
spring:
  task:
    scheduling:
      pool:
        size: 2
      shutdown:
        await-termination: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation_design?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=TRUE&useSSL=FALSE
    username: root
    password: zn.898824


# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.com.backend.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  # JWT加解密使用的密钥
  secret: graduation-design-jwt-secret-key
  # JWT的有效期（单位：秒）
  expiration: 86400

# 爬虫服务配置
crawler:
  base-url: http://127.0.0.1:9999

# AI服务配置
ai:
  deepseek:
    api-key: sk-5b5f00bcaf924b4f965cb8d0486ba187
    base-url: https://api.deepseek.com
  model: deepseek-chat

# 应用基础URL
app:
  base-url: http://localhost:8081

